site_name: My site
site_url: https://SalvadorVelaSanz.github.io
theme:
  name: material
nav:
  - Practica2.1: index.md  # AÃ±ade la referencia a tu archivo index.md
  - Practica2.2: Practica2.md
  - Practica2.3: Practica3.md
  - Practica2.4: Practica4.md

